# Generated by Django 2.1.5 on 2019-08-08 02:27

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20190203_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(validators=[restaurants.models.validate_reservation_time]),
        ),
    ]
